[linux]
server1 ansible_host=44.203.96.77 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/server-audit.pem

[windows]
winserver1 ansible_host=100.59.206.64 ansible_user=Administrator ansible_password=da8ZPz-E!znYFQa=;X-;1ktj&Bi*h&Ya ansible_connection=winrm ansible_winrm_transport=basic ansible_winrm_server_cert_validation=ignore ansible_port=5986